[pytest]
testpaths =
    soundrts/tests
addopts = -ra -q
filterwarnings =
    error
    ignore:.*importlib.*:DeprecationWarning
    ignore:.*getdefaultlocale.*:DeprecationWarning
    ignore:.*pkg_resources is deprecated.*:DeprecationWarning
